---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/clhynfield/concourse-tutorial.git

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: create-some-files
    file: resource-tutorial/11_task_outputs_to_inputs/create_some_files.yml
  - task: show-some-files
    file: resource-tutorial/11_task_outputs_to_inputs/show_files.yml
